#!/usr/bin/env bash

# usage: run [-t] [-c] [-r] [-i INPUT] [YEAR] [DAYS...]
#
#   -t          time execution
#   -c          only compile the source files
#   -r          only run the binaries
#   -i INPUT    use INPUT as the standard input
#
#   run                 # run the current day
#   run YEAR            # run days 1-25 of YEAR
#   run [YEAR] DAYS...  # run given DAYS of YEAR (defaults to current year)

ghcFlags=(
    -O2

    -XAllowAmbiguousTypes
    -XApplicativeDo
    -XBangPatterns
    -XBlockArguments
    -XDeriveGeneric
    -XDerivingVia
    -XFlexibleContexts
    -XFlexibleInstances
    -XGADTs
    -XImportQualifiedPost
    -XLambdaCase
    -XMultiParamTypeClasses
    -XMultiWayIf
    -XNamedFieldPuns
    -XNoMonomorphismRestriction
    -XOverloadedStrings
    -XParallelListComp
    -XRecordWildCards
    -XScopedTypeVariables
    -XStandaloneDeriving
    -XTemplateHaskell
    -XTupleSections
    -XTypeApplications
    -XTypeFamilies
    -XTypeSynonymInstances
    -XViewPatterns
)

log() {
    echo "$(tput setaf 2)✓$(tput sgr0) $*"
}

die() {
    echo "$(tput setaf 1)✗$(tput sgr0) $*" >&2
    exit 1
}

session=$(< .session) || die "No session file found"
export TZ=EST

time=0 runOnly=0 compileOnly=0 forceInput=

while getopts :tcri: o; do case $o in
    t) time=1;;
    c) compileOnly=1;;
    r) runOnly=1;;
    i) forceInput=$2;;
    :) die "Flag -$OPTARG requires an argument";;
    *) die "Invalid flag -$OPTARG";;
esac done

shift "$(( OPTIND - 1 ))"

year=
days=()

if (( $# )); then
    for arg do
        [[ $arg == +([0-9]) ]] || die "Invalid argument \`$arg\`"
        if (( arg > 100 )); then
            year=$arg
        else
            days+=("$arg")
        fi
    done
    year=${year:-$(date +%Y)}
    (( ${#days[@]} )) || days=({1..25})
else
    year=$(date +%Y)
    days=("$(date -d '1 hour' +%-d)")
fi

runAll() for day in "${days[@]}"; do
    printf -v module Day%02d "$day"

    input=inputs/$year/$day bin=bin/$year/$day build=build/$year
    (( ! runOnly )) && mkdir -p "$(dirname "$input")" "$(dirname "$bin")" "$build"

    if (( ! runOnly )) && [[ ! -e $input ]]; then
        log "Downloading input for day $day, $year"
        curl -fsSL -o "$input" -b "session=$session" "https://adventofcode.com/$year/day/$day/input"
    fi

    if (( ! runOnly )); then
        log "Compiling day $day, $year"
        ghc "${ghcFlags[@]}" -isrc -i"src/$year" -outputdir "$build" -o "$bin" -main-is "$module" "src/$year/$module.hs" || exit
    fi

    if (( ! compileOnly )); then
        export AOC_INPUT=${forceInput:-$input}

        (( ! runOnly )) && log "Running day $day, $year"
        if (( time && ${#days[@]} == 1 )); then
            time "$bin"
        else
            "$bin"
        fi
    fi
done

if (( time && ${#days[@]} > 1 )); then
    time runAll
else
    runAll
fi
