#!/bin/bash

time=0

while getopts :t o; do case $o in
    t) time=1;;
esac done

shift "$(( OPTIND - 1 ))"

day=${1:-$(date +%e)}
day=${day#0}
year=${2:-$(date +%Y)}

input=inputs/$year/$day
mkdir -p "$(dirname "$input")"

bin=bin/$year/$day
mkdir -p "$(dirname "$bin")"

build=build/$year
mkdir -p "$build"

if [[ ! -e $input ]]; then
    echo "Downloading input"
    curl -fsSL -o "$input" -b "session=$(< .session)" "https://adventofcode.com/$year/day/$day/input"
fi

run() {
    if [[ -t 0 ]]; then
        ./"$bin" < "$input"
    else
        ./"$bin"
    fi
}

if ghc -O2 -dynamic -isrc -i"src/$year" -outputdir "$build" -o "$bin" -main-is "Day$day" "src/$year/$day.hs"; then
    echo "Running $bin"
    if (( time )); then
        time run
    else
        run
    fi
fi
